# docker-compose.yml

services:
  # Serviço do banco de dados (sem alterações)
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: mugiwara_store
      POSTGRES_USER: luffy
      POSTGRES_PASSWORD: meusonhoeh
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Serviço do Backend Flask
  backend:
    build: ./mugiwara-store-backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./mugiwara-store-backend:/app
    # Passa as variáveis de ambiente para o container do backend
    environment:
      - POSTGRES_DB=mugiwara_store
      - POSTGRES_USER=luffy
      - POSTGRES_PASSWORD=meusonhoeh
      - DB_HOST=db # Aponta para o serviço 'db'
      - FLASK_ENV=development 
      - FLASK_APP=app.py
    depends_on:
      - db