# Nossos serviços (as "caixinhas")
services:
  # O serviço do nosso banco de dados
  db:
    # A imagem oficial do PostgreSQL, versão 16 (pode escolher outra)
    image: postgres:16
    # Sempre reiniciar o container se ele parar
    restart: always
    # Variáveis de ambiente para configurar o banco na primeira vez que ele rodar
    environment:
      POSTGRES_DB: mugiwara_store
      POSTGRES_USER: luffy
      POSTGRES_PASSWORD: meusonhoeh
    # Mapeia a porta 5432 de dentro da "caixinha" para a porta 5432 da sua máquina
    ports:
      - "5432:5432"
    # IMPORTANTE: Garante que os dados do banco fiquem salvos no seu computador
    volumes:
      - ./postgres-data:/var/lib/postgresql/data