services:
  # Serviço do banco de dados
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: mugiwara_store
      POSTGRES_USER: luffy
      POSTGRES_PASSWORD: meusonhoeh
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Serviço do Backend Flask
  backend:
    # 'build' instrui o Docker Compose a construir uma imagem
    # a partir do Dockerfile localizado na pasta especificada.
    build: ./mugiwara-store-backend
    restart: always
    # Mapeia a porta 5000 do container para a porta 5000 da sua máquina.
    ports:
      - "5000:5000"
    # Monta o código do backend como um volume.
    volumes:
      - ./mugiwara-store-backend:/app
    # 'depends_on' garante que o serviço 'db' seja iniciado antes do 'backend'.
    depends_on:
      - db